version: "3.9"

services:
  yt-scraper:
    build: .
    stdin_open: true
    tty: true
    environment:
      - YOUTUBE_API_KEY
      - YOUTUBE_API_PAGE_SIZE=50
      - SPLUNK_HEC_TOKEN
      - SPLUNK_HEC_BASE_URL
#      - DISABLE_SPLUNK_HEC=1
    volumes:
      - ./db:/app/db
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN
      - SPLUNK_PASSWORD
    ports:
      - 8000:8000
      - 8088:8088
